### ISSUE TITLE
Investigate root cause

### ISSUE THREAD

**Issue by Amorrison6** [DaveChamberlain/casim#12]
Not sure what needs to change in order to get a window to expand.  Is this a global setting or per-window or pane?

**Comment by andrea-couto** [comment]
Currently investigating the cause of the main window not scaling the background motherboard image. 
The image that is used is "/resource/Motherboard3.png" which is defined as backgroundimage line 541 of ComputerGUI.java.
It is drawn in paintComponent but the image has an overlay of ports that are drawn in showPorts() which uses hard-coded values  from line 673 in ComputerGUI.java.

Meaning, if we scale the background image, we would also need to dynamically find the values where the ports should be drawn.

**Comment by DaveChamberlain** [comment]
This is pretty messy.   The frames being used are JInternalFrames, which apparently, based on the theme, may not have a resize handle.  However, a maximize works so might need to consider that as a way of handling making it larger.

**Comment by DaveChamberlain** [comment]
The reason that the components weren't being redrawn is that the 'repaint' method never looks at them.  Need to add some code to the repaint to fix the size on the container and adjust the heights of anything in the container.
